/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorSol from "./Governor.sol";
export type { governorSol };
import type * as timeLockControllerSol from "./TimeLockController.sol";
export type { timeLockControllerSol };
export type { ExternalContract } from "./ExternalContract";
export type { VoteToken } from "./VoteToken";
