/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governorSol from "./Governor.sol";
export * as timeLockControllerSol from "./TimeLockController.sol";
export { ExternalContract__factory } from "./ExternalContract__factory";
export { VoteToken__factory } from "./VoteToken__factory";
